package com.sysdt.lock.dao;

import com.sysdt.lock.model.Historico;
import com.sysdt.lock.model.HistoricoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoricoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int countByExample(HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int deleteByExample(HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int insert(Historico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int insertSelective(Historico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    List<Historico> selectByExample(HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    Historico selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") Historico record, @Param("example") HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int updateByExample(@Param("record") Historico record, @Param("example") HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int updateByPrimaryKeySelective(Historico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Jan 21 09:55:21 CST 2017
     */
    int updateByPrimaryKey(Historico record);
}