package com.sysdt.lock.model;

import java.io.Serializable;

public class Cliente implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3240514591710186586L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.id
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.nombre
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.logo
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.ancho
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private Integer ancho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.alto
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private String alto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.id
     *
     * @return the value of cliente.id
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.id
     *
     * @param id the value for cliente.id
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.nombre
     *
     * @return the value of cliente.nombre
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.nombre
     *
     * @param nombre the value for cliente.nombre
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.logo
     *
     * @return the value of cliente.logo
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.logo
     *
     * @param logo the value for cliente.logo
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.ancho
     *
     * @return the value of cliente.ancho
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public Integer getAncho() {
        return ancho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.ancho
     *
     * @param ancho the value for cliente.ancho
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setAncho(Integer ancho) {
        this.ancho = ancho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.alto
     *
     * @return the value of cliente.alto
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public String getAlto() {
        return alto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.alto
     *
     * @param alto the value for cliente.alto
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setAlto(String alto) {
        this.alto = alto;
    }
}