package com.sysdt.lock.model;

import java.io.Serializable;

public class TipoUsuario implements Serializable {
	
	private static final long serialVersionUID = -3814850685574380344L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipo_usuario.id
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipo_usuario.tipo
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    private String tipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipo_usuario.id
     *
     * @return the value of tipo_usuario.id
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipo_usuario.id
     *
     * @param id the value for tipo_usuario.id
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipo_usuario.tipo
     *
     * @return the value of tipo_usuario.tipo
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipo_usuario.tipo
     *
     * @param tipo the value for tipo_usuario.tipo
     *
     * @mbggenerated Sat Jul 23 14:42:17 CDT 2016
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}