package com.sysdt.lock.model;

import java.io.Serializable;

public class Unidad implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad.id
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad.eco
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    private String eco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad.token
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad.idCliente
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    private Integer idcliente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad.id
     *
     * @return the value of unidad.id
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad.id
     *
     * @param id the value for unidad.id
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad.eco
     *
     * @return the value of unidad.eco
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public String getEco() {
        return eco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad.eco
     *
     * @param eco the value for unidad.eco
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public void setEco(String eco) {
        this.eco = eco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad.token
     *
     * @return the value of unidad.token
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad.token
     *
     * @param token the value for unidad.token
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad.idCliente
     *
     * @return the value of unidad.idCliente
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad.idCliente
     *
     * @param idcliente the value for unidad.idCliente
     *
     * @mbggenerated Sat Jan 21 22:12:14 CST 2017
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
}